/* Senderos — carrito: servicios + productos + reservas + pago */
const API_TURNOS='../api/turnos.php';
const API_PEDIDOS='../api/pedidos.php';
const COSTO_ENVIO=800;
let carritoData=[];
let entregaActual='retiro';
let pagoSeleccion='todo';
let metodoPago='efectivo';
let turnosAsignados={};
const SLOTS=['09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:30','14:00','14:30','15:00','15:30','16:00','16:30','17:00','17:30','18:00','18:30','19:00','19:30','20:00'];

document.addEventListener('DOMContentLoaded',()=>{ actualizarNavbar?.(); cargarCarrito(); document.getElementById('navbar')?.classList.toggle('scrolled',scrollY>20); addEventListener('scroll',()=>document.getElementById('navbar')?.classList.toggle('scrolled',scrollY>20),{passive:true}); });
function cargarCarrito(){ carritoData=JSON.parse(localStorage.getItem('carrito')||'[]'); const ss=carritoData.filter(i=>i.tipo==='servicio'), pp=carritoData.filter(i=>i.tipo==='producto'); const empty=document.getElementById('cartEmpty'), layout=document.getElementById('cartLayout'); if(!carritoData.length){empty.classList.remove('hidden');layout.classList.add('hidden');return;} empty.classList.add('hidden');layout.classList.remove('hidden'); renderTabs(ss.length,pp.length);renderServicios(ss);renderProductos(pp);renderResumen(); }
function renderTabs(ns,np){const t=document.getElementById('cartTabs');t.innerHTML='';if(ns){t.appendChild(makeTab('services','servicio.svg','Servicios',ns));}if(np){t.appendChild(makeTab('products','bolsa.svg','Productos',np));}switchTab(ns?'services':'products');}
function makeTab(sec,icon,label,n){const b=document.createElement('button');b.className='cart-tab';b.dataset.sec=sec;b.innerHTML=`<img src="../img/icons/${icon}" alt="" width="15" height="15"> ${label}<span>${n}</span>`;b.onclick=()=>switchTab(sec);return b;}
function switchTab(sec){document.querySelectorAll('.cart-tab').forEach(x=>x.classList.toggle('active',x.dataset.sec===sec));document.getElementById('secServices')?.classList.toggle('hidden',sec!=='services');document.getElementById('secProducts')?.classList.toggle('hidden',sec!=='products');}
function renderServicios(lista){const sec=document.getElementById('secServices'),cont=document.getElementById('listaServicios');if(!lista.length){sec.classList.add('hidden');return;}sec.classList.remove('hidden');document.getElementById('servCount').textContent=lista.length;cont.innerHTML=lista.map((it,i)=>{const a=turnosAsignados[i];return `<article class="cart-item"><div class="item-img-wrap"><img src="${safe(it.img)}" alt="${safe(it.nombre)}" onerror="this.style.display='none'"></div><div class="item-info"><span class="item-type service"><img src="../img/icons/servicio.svg" alt="" width="13" height="13"> Servicio</span><h3>${safe(it.nombre)}</h3><p class="item-meta">${it.duracion?`<img src="../img/icons/tiempo.svg" alt="" width="13" height="13"> ${safe(it.duracion)}`:''}</p>${a?`<div class="assigned"><img src="../img/icons/calendario.svg" alt="" width="14" height="14"><span>${fechaBonita(a.fecha)} · ${a.horario} hs</span><button onclick="abrirAsignacion(${i})">Cambiar</button></div>`:`<button class="btn-asignar-turno" onclick="abrirAsignacion(${i})"><img src="../img/icons/calendario.svg" alt="" width="15" height="15"> Elegir fecha y horario</button>`}</div><div class="item-price-col"><strong>$${money(it.precio)}</strong><button class="item-remove" onclick="quitarServicio(${i})" title="Quitar"><img src="../img/icons/x.svg" alt="Quitar" width="14" height="14"></button></div></article>`}).join('');renderAsignaciones(lista);}
function renderAsignaciones(lista){const block=document.getElementById('reservaBlock'),cont=document.getElementById('reservaItems');const falt=lista.map((x,i)=>i).filter(i=>!turnosAsignados[i]);if(!falt.length){block.innerHTML='<div class="all-assigned"><img src="../img/icons/check.svg" alt="" width="18" height="18"><div><strong>Todos los servicios tienen turno.</strong><span>Podés cambiar cualquier fecha u horario antes de confirmar.</span></div></div>';return;}cont.innerHTML=falt.map(i=>`<div class="asig-item"><div class="asig-head"><strong>${safe(lista[i].nombre)}</strong><button onclick="toggleAsig(${i})">Elegir fecha y horario ↓</button></div><div id="asigBody_${i}" class="asig-body hidden"><div id="miniCal_${i}"></div><div id="asigHors_${i}" class="asig-horarios hidden"><p>Horarios disponibles</p><div id="hGrid_${i}" class="horarios-grid"></div></div></div></div>`).join('');}
function abrirAsignacion(i){switchTab('services');const el=document.querySelectorAll('.asig-item')[0];toggleAsig(i,true);setTimeout(()=>document.getElementById('asigItem_'+i)?.scrollIntoView({behavior:'smooth',block:'center'}),50);}
function toggleAsig(i,force=false){const b=document.getElementById('asigBody_'+i);if(!b)return;const open=force||b.classList.contains('hidden');b.classList.toggle('hidden',!open);if(open)buildMiniCal(i);}
function buildMiniCal(i){const c=document.getElementById('miniCal_'+i),d=new Date(),y=d.getFullYear(),m=d.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),names=['D','L','M','M','J','V','S'];let h=`<div class="mcal-title">${d.toLocaleDateString('es-AR',{month:'long',year:'numeric'})}</div><div class="mcal-dow">${names.map(x=>`<span>${x}</span>`).join('')}</div><div class="mcal-grid">`;for(let x=0;x<first;x++)h+='<span></span>';for(let day=1;day<=days;day++){const f=new Date(y,m,day),past=f<new Date(d.getFullYear(),d.getMonth(),d.getDate()),sun=f.getDay()===0;const fs=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;h+=`<button class="mcal-day ${past||sun?'dis':''}" ${past||sun?'disabled':''} onclick="selFecha('${fs}',${i},this)">${day}</button>`}c.innerHTML=h+'</div>';}
async function selFecha(fecha,i,btn){btn.closest('.mcal-grid')?.querySelectorAll('.sel').forEach(x=>x.classList.remove('sel'));btn.classList.add('sel');const h=document.getElementById('asigHors_'+i);h.classList.remove('hidden');const grid=document.getElementById('hGrid_'+i);grid.innerHTML='<span class="loading">Consultando disponibilidad…</span>';let ocupados=[];try{const r=await fetch(`${API_TURNOS}?fecha=${encodeURIComponent(fecha)}`);const data=await r.json();if(data.ok)ocupados=data.turnos||[]}catch(e){}const srv=carritoData.filter(x=>x.tipo==='servicio')[i];const dur=Math.max(30,parseInt(srv?.duracion)||30);grid.innerHTML='';SLOTS.forEach(slot=>{const ok=slotLibre(slot,dur,ocupados);const b=document.createElement('button');b.className='horario-btn'+(ok?'':' ocupado');b.disabled=!ok;b.textContent=slot;if(ok)b.onclick=()=>selHorario(fecha,slot,i,b);grid.appendChild(b);});}
function slotLibre(slot,dur,ocupados){const ini=minutos(slot),fin=ini+dur;if(fin>21*60)return false;return !ocupados.some(t=>{if(t.estado==='cancelado')return false;const ti=minutos(String(t.horario).slice(0,5)),tf=ti+(Number(t.duracion_total)||30);return ini<tf&&fin>ti;});}
function selHorario(fecha,horario,i,btn){document.querySelectorAll(`#hGrid_${i} .horario-btn`).forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');turnosAsignados[i]={fecha,horario};renderServicios(carritoData.filter(x=>x.tipo==='servicio'));renderResumen();}
function renderProductos(lista){const sec=document.getElementById('secProducts'),cont=document.getElementById('listaProductos');if(!lista.length){sec.classList.add('hidden');return;}sec.classList.remove('hidden');const grouped={};lista.forEach((it,idx)=>{const k=it.id??it.nombre;(grouped[k]??={...it,cantidad:0,idxs:[]}).cantidad++;grouped[k].idxs.push(idx);});const arr=Object.values(grouped);document.getElementById('prodCount').textContent=lista.length;cont.innerHTML=arr.map(it=>`<article class="cart-item product-item"><div class="item-img-wrap"><img src="${safe(it.img)}" alt="${safe(it.nombre)}" onerror="this.style.display='none'"></div><div class="item-info"><span class="item-type product"><img src="../img/icons/bolsa.svg" alt="" width="13" height="13"> Producto</span><h3>${safe(it.nombre)}</h3><p class="item-meta">$${money(it.precio)} c/u</p></div><div class="qty-control"><button onclick="cambiarCantidad('${esc(it.id??it.nombre)}',-1)">−</button><b>${it.cantidad}</b><button onclick="cambiarCantidad('${esc(it.id??it.nombre)}',1)">+</button></div><div class="item-price-col"><strong>$${money(it.precio*it.cantidad)}</strong><button class="item-remove" onclick="quitarTodos('${esc(it.id??it.nombre)}')"><img src="../img/icons/x.svg" alt="Quitar" width="14" height="14"></button></div></article>`).join('');}
function quitarServicio(i){const ss=carritoData.filter(x=>x.tipo==='servicio');const item=ss[i];const idx=carritoData.indexOf(item);if(idx>=0)carritoData.splice(idx,1);reindexTurnos();saveReload();}
function quitarTodos(key){carritoData=carritoData.filter(i=>!(i.tipo==='producto'&&String(i.id??i.nombre)===String(key)));saveReload();}
function cambiarCantidad(key,delta){if(delta>0){const base=carritoData.find(i=>i.tipo==='producto'&&String(i.id??i.nombre)===String(key));if(base)carritoData.push({...base});}else{for(let i=carritoData.length-1;i>=0;i--){const x=carritoData[i];if(x.tipo==='producto'&&String(x.id??x.nombre)===String(key)){carritoData.splice(i,1);break;}}}saveReload();}
function reindexTurnos(){const old=turnosAsignados,newMap={};carritoData.filter(x=>x.tipo==='servicio').forEach((_,i)=>{if(old[i])newMap[i]=old[i]});turnosAsignados=newMap;}
function saveReload(){localStorage.setItem('carrito',JSON.stringify(carritoData));actualizarNavbar?.();cargarCarrito();}
function seleccionarEntrega(t){entregaActual=t;document.getElementById('opRetiro')?.classList.toggle('active',t==='retiro');document.getElementById('opEnvio')?.classList.toggle('active',t==='envio');document.getElementById('envioForm')?.classList.toggle('hidden',t==='retiro');renderResumen();}
function selPago(v){pagoSeleccion=v;document.querySelectorAll('.pago-opt').forEach(x=>x.classList.toggle('active',x.dataset.pago===v));renderResumen();}
function selMetodoPago(v){metodoPago=v;document.querySelectorAll('.method-option').forEach(x=>x.classList.toggle('active',x.querySelector('input')?.value===v));}
function renderResumen(){const ss=carritoData.filter(i=>i.tipo==='servicio'),pp=carritoData.filter(i=>i.tipo==='producto'),ts=ss.reduce((a,i)=>a+Number(i.precio||0),0),tp=pp.reduce((a,i)=>a+Number(i.precio||0),0),env=entregaActual==='envio'&&pp.length?COSTO_ENVIO:0;let lines='';if(ss.length)lines+=`<div class="sum-line"><span>Servicios (${ss.length})</span><b>$${money(ts)}</b></div>`;if(pp.length)lines+=`<div class="sum-line"><span>Productos (${pp.length})</span><b>$${money(tp)}</b></div>`;if(env)lines+=`<div class="sum-line"><span>Envío</span><b>$${money(env)}</b></div>`;document.getElementById('sumLines').innerHTML=lines;const ambos=ss.length&&pp.length;const opts=document.getElementById('pagoOpts');opts.innerHTML=ambos?[['todo','Todo junto',ts+tp+env],['servicios','Solo servicios',ts],['productos','Solo productos',tp+env]].map(x=>`<label class="pago-opt ${pagoSeleccion===x[0]?'active':''}" data-pago="${x[0]}"><input type="radio" name="pago" value="${x[0]}" ${pagoSeleccion===x[0]?'checked':''} onchange="selPago('${x[0]}')"><span><b>${x[1]}</b><strong>$${money(x[2])}</strong></span></label>`).join(''):'';if(!ambos)pagoSeleccion='todo';const total=pagoSeleccion==='servicios'?ts:pagoSeleccion==='productos'?tp+env:ts+tp+env;document.getElementById('sumTotal').textContent='$'+money(total);document.getElementById('btnPagar').disabled=!carritoData.length;}
async function procesarPago(){if(!requireSesion('completar tu pedido'))return;const ss=carritoData.filter(i=>i.tipo==='servicio'),pp=carritoData.filter(i=>i.tipo==='producto');if(pagoSeleccion!=='productos'&&ss.some((_,i)=>!turnosAsignados[i])){showToast('Asigná fecha y horario a todos los servicios.');switchTab('services');document.getElementById('reservaBlock')?.scrollIntoView({behavior:'smooth'});return;}if(entregaActual==='envio'&&pagoSeleccion!=='servicios'&&!document.getElementById('envDireccion')?.value.trim()){showToast('Ingresá la dirección de envío.');return;}const ts=ss.reduce((a,i)=>a+Number(i.precio||0),0),tp=pp.reduce((a,i)=>a+Number(i.precio||0),0),env=entregaActual==='envio'&&pp.length?COSTO_ENVIO:0;const groups=[];if(pagoSeleccion!=='productos'&&ss.length){ss.forEach((s,i)=>groups.push({s,as:turnosAsignados[i]}));}const btn=document.getElementById('btnPagar');btn.disabled=true;btn.textContent='Guardando…';try{
  // Primero crear pedido(s), para que la reserva pueda quedar asociada al pedido.
  const pedidos=[];
  const makeItems=arr=>{const m={};arr.forEach(p=>{const k=p.id??p.nombre;if(!m[k])m[k]={...p,cantidad:0};m[k].cantidad++;});return Object.values(m).map(p=>({producto_id:p.id??null,nombre:p.nombre,precio:Number(p.precio||0),cantidad:p.cantidad,tipo:p.tipo==='servicio'?'servicio':'producto',servicio_id:p.tipo==='servicio'?(p.id??null):null}));};
  const crearPedido=async(items,total)=>{const r=await fetch(API_PEDIDOS,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({total,items,metodo_pago:metodoPago,entrega:entregaActual,direccion_envio:document.getElementById('envDireccion')?.value.trim()||null,pago_grupo:pagoSeleccion})});const d=await r.json();if(!d.ok)throw new Error(d.error||'No se pudo crear el pedido');pedidos.push(d);return d;};
  let pedidoServ=null,pedidoProd=null;if(pagoSeleccion==='todo') {const items=[...makeItems(ss),...makeItems(pp)];const d=await crearPedido(items,ts+tp+env);pedidoServ=d.id;pedidoProd=d.id;} else {if(pagoSeleccion!=='productos'&&ss.length)pedidoServ=(await crearPedido(makeItems(ss),ts)).id;if(pagoSeleccion!=='servicios'&&pp.length)pedidoProd=(await crearPedido(makeItems(pp),tp+env)).id;}
  // Crear turnos reales en BD; el endpoint vuelve a validar solapamientos.
  for(const g of groups){const r=await fetch(API_TURNOS,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fecha:g.as.fecha,horario:g.as.horario,duracion_total:parseInt(g.s.duracion)||30,precio_total:Number(g.s.precio||0),servicios:[{id:g.s.id??null,nombre:g.s.nombre,duracion:parseInt(g.s.duracion)||30,precio:Number(g.s.precio||0)}],pedido_id:pedidoServ,metodo_pago:metodoPago})});const d=await r.json();if(!d.ok)throw new Error(d.error||'No se pudo reservar el turno');}
  sessionStorage.setItem('ultimoPedidoId',pedidoProd||pedidoServ||'');sessionStorage.setItem('ultimoMetodoPago',metodoPago);sessionStorage.setItem('ultimoPagoGrupo',pagoSeleccion);localStorage.removeItem('carrito');window.location.href='confirmacion.html';
}catch(e){showToast(e.message||'No se pudo completar la operación.');btn.disabled=false;btn.textContent='Confirmar pedido y reserva';}}
function fechaBonita(s){try{return new Date(s+'T00:00:00').toLocaleDateString('es-AR',{weekday:'short',day:'numeric',month:'short'});}catch{return s;}}
function minutos(s){const [h,m]=String(s).split(':').map(Number);return h*60+m;}
function money(n){return Number(n||0).toLocaleString('es-AR');}
function safe(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function esc(v){return String(v??'').replace(/'/g,"\\'");}
function showToast(msg){const t=document.getElementById('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.remove('show'),3200);}
